import kbSeed from "@/data/kb-seed.json";

/**
 * Knowledge base access. The KB is a local JSON file, READ-ONLY at runtime.
 * The monthly cron is its only writer. Never mutate the loaded object.
 *
 * Each category holds raw facts; the runtime comparison is generated by the LLM
 * from these facts + the user input. See CLAUDE.md "Data model".
 */

export type Tension = "alta" | "media" | "bassa";

export interface CommonSolution {
  name: string;
  type: "saas" | "onprem" | "nocode";
  priceRange: string;
  bestFor: string;
  limitations: string;
}

export interface TypicalCustomCost {
  range: string;
  timeline: string;
  maintenanceNote: string;
}

export interface KbCategory {
  id: string;
  name: string;
  aliases: string[];
  description: string;
  tension: Tension;
  commonSolutions: CommonSolution[];
  typicalCustomCost: TypicalCustomCost;
  whenBuildWins: string;
  updatedAt: string;
}

export interface KnowledgeBase {
  version: string;
  lastUpdated: string;
  categories: KbCategory[];
}

const kb = kbSeed as unknown as KnowledgeBase;

/** All categories. Treat the result as immutable. */
export function getCategories(): readonly KbCategory[] {
  return kb.categories;
}

/** Stable list of valid category ids — used to constrain LLM classification. */
export function getCategoryIds(): string[] {
  return kb.categories.map((c) => c.id);
}

/** Look up a category by its exact id. */
export function getCategoryById(id: string): KbCategory | undefined {
  return kb.categories.find((c) => c.id === id);
}

const normalize = (s: string) =>
  s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // strip accents
    .trim();

/**
 * Cheap deterministic fallback match: scan id, name and aliases for a substring
 * hit against the user's text. Returns the best (longest-alias) match or
 * undefined. The primary classifier is the LLM (Phase 3); this is the safety net
 * so we never depend on a model call to find an obvious category.
 */
export function matchCategoryByText(text: string): KbCategory | undefined {
  const hay = normalize(text);
  let best: { category: KbCategory; score: number } | undefined;

  for (const category of kb.categories) {
    const needles = [category.id.replace(/-/g, " "), category.name, ...category.aliases];
    for (const needle of needles) {
      const n = normalize(needle);
      if (n.length >= 3 && hay.includes(n)) {
        const score = n.length;
        if (!best || score > best.score) best = { category, score };
      }
    }
  }

  return best?.category;
}

export const kbVersion = kb.version;
export const kbLastUpdated = kb.lastUpdated;
