import kbSeed from "@/data/kb-seed.json";
import { getClient, DbNotConfiguredError } from "./db";

/**
 * Knowledge base access. Source of truth is Turso (table `kb_doc`, one JSON
 * document); `data/kb-seed.json` is the bootstrap seed + fallback. The monthly
 * cron is the KB's only writer. Read at runtime is cached and READ-ONLY.
 *
 * Each category holds raw facts; the runtime comparison is generated by the LLM
 * from these facts + the user input.
 */

export type Tension = "alta" | "media" | "bassa";

export interface CommonSolution {
  name: string;
  type: "saas" | "onprem" | "nocode";
  priceRange: string;
  bestFor: string;
  limitations: string;
}

export interface TypicalCustomCost {
  range: string;
  timeline: string;
  maintenanceNote: string;
}

export interface KbCategory {
  id: string;
  name: string;
  aliases: string[];
  description: string;
  tension: Tension;
  commonSolutions: CommonSolution[];
  typicalCustomCost: TypicalCustomCost;
  whenBuildWins: string;
  updatedAt: string;
}

export interface KnowledgeBase {
  version: string;
  lastUpdated: string;
  categories: KbCategory[];
}

const SEED = kbSeed as unknown as KnowledgeBase;

const CACHE_TTL_MS = 10 * 60 * 1000; // KB changes monthly; 10 min staleness is fine
let cache: { kb: KnowledgeBase; at: number } | undefined;

async function ensureKbSchema(client: ReturnType<typeof getClient>): Promise<void> {
  await client.execute(
    `CREATE TABLE IF NOT EXISTS kb_doc (
      id         INTEGER PRIMARY KEY CHECK (id = 1),
      doc        TEXT NOT NULL,
      version    TEXT NOT NULL,
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    )`,
  );
}

/**
 * Load the KB: Turso first (cached), falling back to the bundled seed when Turso
 * is unconfigured, unreachable, or not yet populated. Pass { fresh } to bypass
 * the cache (used by the cron before refreshing).
 */
export async function loadKb(opts?: { fresh?: boolean }): Promise<KnowledgeBase> {
  if (!opts?.fresh && cache && Date.now() - cache.at < CACHE_TTL_MS) {
    return cache.kb;
  }

  let kb: KnowledgeBase = SEED;
  try {
    const client = getClient();
    await ensureKbSchema(client);
    const res = await client.execute("SELECT doc FROM kb_doc WHERE id = 1");
    const doc = res.rows[0]?.doc;
    if (typeof doc === "string") kb = JSON.parse(doc) as KnowledgeBase;
  } catch (err) {
    if (!(err instanceof DbNotConfiguredError)) {
      console.error("[kb] load from Turso failed, using seed:", err);
    }
    kb = SEED;
  }

  cache = { kb, at: Date.now() };
  return kb;
}

/** Persist the KB to Turso (cron only). Throws if Turso isn't configured. */
export async function saveKb(kb: KnowledgeBase): Promise<void> {
  const client = getClient();
  await ensureKbSchema(client);
  await client.execute({
    sql: `INSERT INTO kb_doc (id, doc, version, updated_at) VALUES (1, ?, ?, datetime('now'))
          ON CONFLICT (id) DO UPDATE SET doc = excluded.doc, version = excluded.version, updated_at = excluded.updated_at`,
    args: [JSON.stringify(kb), kb.version],
  });
  cache = { kb, at: Date.now() };
}

const normalize = (s: string) =>
  s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // strip accents
    .trim();

/**
 * Cheap deterministic match: scan id, name and aliases for a substring hit
 * against the user's text. Returns the best (longest-alias) match or undefined.
 * The primary classifier is the LLM; this is the safety net so we never depend
 * on a model call to find an obvious category.
 */
export function matchCategoryByText(
  categories: readonly KbCategory[],
  text: string,
): KbCategory | undefined {
  const hay = normalize(text);
  let best: { category: KbCategory; score: number } | undefined;

  for (const category of categories) {
    const needles = [category.id.replace(/-/g, " "), category.name, ...category.aliases];
    for (const needle of needles) {
      const n = normalize(needle);
      if (n.length >= 3 && hay.includes(n)) {
        const score = n.length;
        if (!best || score > best.score) best = { category, score };
      }
    }
  }

  return best?.category;
}
